namespace: ThelioMcFly
name: ansible_workstation
version: 0.1.0
readme: README.md
authors:
- ThelioMcFly
description: This collection will allow a new workstation install to be configured quickly

tags: 
  - ThelioMcFly
  - Workstation

dependencies: {}
repository: https://github.com/ThelioMcFly/ansible-workstation
documentation: https://github.com/ThelioMcFly/ansible-workstation/blob/main/README.md
homepage: https://github.com/ThelioMcFly/ansible-workstation
issues: https://github.com/ThelioMcFly/ansible-workstation/issues

build_ignore: 
  - .git

