namespace: theliomcfly
name: workstation
version: 0.2.0
readme: README.md
authors:
- ThelioMcFly
description: This collection will allow a new workstation install to be configured quickly

tags: 
  - ThelioMcFly
  - Workstation

license:
  - Apache-2.0

dependencies: 
  "community.general": ">=4.4.0"
  
repository: https://github.com/ThelioMcFly/ansible-workstation
documentation: https://github.com/ThelioMcFly/ansible-workstation/blob/main/README.md
homepage: https://github.com/ThelioMcFly/ansible-workstation
issues: https://github.com/ThelioMcFly/ansible-workstation/issues

build_ignore: 
  - .git

