galaxy_info:
  author: ThelioMcFly
  description: Add/Edit/Remove Gnome settings in dconf
  min_ansible_version: "2.12"
  license: ""
  galaxy_tags: 
    - gnome
    - dconf
dependencies: 
  - role: "community.general.dconf"