---

- name: Include OS specific vars
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Install Terraform

  block:
  - name: Install required dependencies
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items: "{{ terraform_required_dep_packages }}"

  - name: Install Hashicorp repository
    ansible.builtin.shell:
      cmd: "sudo dnf config-manager --add-repo {{ terraform_required_repo }}"
      creates: /etc/yum.repos.d/hashicorp.repo
      
  - name: Install Terraform package
    ansible.builtin.package:
      name: terraform
      state: present
  become: true