---
- name: "Include vars for {{ansible_facts['distribution']}}"
  include_vars: "{{ansible_facts['distribution']}}.yml"

- name: Ensure psutils is installed
  become: true
  ansible.builtin.package:
    name: "{{psutils_pkg_name}}"
    state: present

- name: Set specified configurations
  become: "{{item.dconf_user is defined | ternary(true,false)}}"
  become_user: "{{item.dconf_user |default('remote_user')}}"
  community.general.dconf:
    key: "{{item.dconf_settings.key}}"
    value: "'{{item.dconf_settings.value }}'"
    state: "{{item.dconf_settings.state}}"
  with_items: "{{config}}"
  when: config is defined
